language: rust
rust:
  - nightly

dist: xenial
cache:
  apt: true
  cargo: true
  timeout: 1000 #In seconds
  directories:
    - $TRAVIS_BUILD_DIR/riscv
    - $TRAVIS_BUILD_DIR/llvm-9

git:
  submodules: false
  depth: 1

env:
  - RISCV=$TRAVIS_BUILD_DIR/riscv PATH=$PATH:$RISCV/bin PATH=$PATH:TRAVIS_BUILD_DIR/llvm-9

addons:
  apt:
    packages:
    - autoconf
    - automake
    - autotools-dev
    - build-essential
    - gcc
    - git

branches:
  only:
    - keystone

before_install:
  - rustup target add riscv64gc-unknown-none-elf
  - rustup component add rust-src
  - cargo install cargo-xbuild || true
  - ./.fast-setup.sh

jobs:
  include:
    - stage: build everything
      script:
        - mkdir build
        - cd build
        - ../configure
          --enable-logo
          --host=riscv64-unknown-elf
          --enable-sm
        - make

    - stage: test
      script:
        - if [ -f riscv/bin/qemu-riscv64 ]; then ls riscv; else ./.build-qemu.sh; fi
        - ./test-sm.sh

